<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\CoworkingManager.Models\CoworkingManager.Models.csproj" />
    <ProjectReference Include="..\..\CoworkingManager.Services\CoworkingManager.Services.csproj" />
    <ProjectReference Include="..\CoworkingManager.Client\CoworkingManager.Client.csproj" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" Version="10.0.8" />
    <PackageReference Include="MySqlConnector" Version="2.5.0" />
  </ItemGroup>

</Project>
